- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    update: yes

- name: Symlink dotfiles
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  loop:
    - { src: '.dotfiles/.zshrc', dest: '.zshrc' }
    - { src: '.dotfiles/.tmux.conf', dest: '.tmux.conf' }
