- name: Add Microsoft apt key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    update_cache: yes

- name: Install selected VSCode extensions
  become: false
  vars:
    vscode_extensions:
      - ms-python.python
      - ms-vscode.cpptools
  ansible.builtin.command: "code --install-extension {{ item }} --force"
  loop: "{{ vscode_extensions }}"
