- name: Add Microsoft apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true

- name: Add VSCode repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    update_cache: yes
  become: true

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
    update_cache: yes
  become: true
   
- name: Install selected VSCode extensions
  become: false
  vars:
    vscode_extensions:
      - ms-python.python
      - ms-vscode.cpptools
  command: "code --install-extension {{ item }} --force"
  loop: "{{ vscode_extensions }}"
