- name: Ensure sdkmanager prerequisites are installed
  apt:
    name: wget,unzip
    state: present

- name: Create SDK directory
  file:
    path: "{{ sdk_root }}"
    state: directory
    mode: '0755'

- name: Download Android cmdline-tools
  get_url:
    url: https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
    dest: /tmp/cmdline-tools.zip
    mode: '0644'
  register: got_tools

- name: Unpack cmdline-tools
  unarchive:
    src: /tmp/cmdline-tools.zip
    dest: "{{ sdk_root }}"
    creates: "{{ sdk_root }}/cmdline-tools"
  when: got_tools is changed

- name: Add sdkmanager & adb to PATH in bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    insertafter: EOF
    line: |
      export ANDROID_SDK_ROOT="{{ sdk_root }}"
      export PATH="$PATH:{{ sdk_root }}/cmdline-tools/bin:{{ sdk_root }}/platform-tools"

- name: Install SDK packages (platform-tools, build-tools, platform)
  community.general.android_sdk:
    name:
      - platform-tools
      - "build-tools;34.0.0"
      - "platforms;android-34"
    sdk_root: "{{ sdk_root }}"
    accept_licenses: true
    state: latest

- name: Create NDK directory
  file:
    path: "{{ ndk_root }}"
    state: directory
    mode: '0755'

- name: Download Android NDK
  get_url:
    url: "https://dl.google.com/android/repository/android-ndk-{{ ndk_version }}-linux.zip"
    dest: "/tmp/android-ndk-{{ ndk_version }}.zip"
    mode: '0644'

- name: Unpack Android NDK
  unarchive:
    src: "/tmp/android-ndk-{{ ndk_version }}.zip"
    dest: "{{ ndk_root }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "{{ ndk_root }}/source.properties"

- name: Add NDK to bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    insertafter: EOF
    line: |
      export ANDROID_NDK_ROOT="{{ ndk_root }}"
      export PATH="$PATH:{{ ndk_root }}"

- name: Source bashrc for current session (optional)
  shell: source "{{ ansible_env.HOME }}/.bashrc"
  args:
    executable: /bin/bash
